hosts:
  localhost: 127.0.0.1

install:
  - move jcePolicy\local_policy.jar %JAVA_HOME%\jre\lib\security
  - move jcePolicy\US_export_policy.jar %JAVA_HOME%\jre\lib\security
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test findbugs:check jacoco:report coveralls:report -P h2

build: off